{% set version = "4.3.1" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://github.com/neo4j/neo4j-python-driver/archive/{{ version }}.tar.gz
  sha256: d652f101e832d734731bef8336b139baf43787b2f725658d7b7e48f88dfee8b8

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.5
    - cython
    - pip
  run:
    - python >=3.5
    - pytz

test:
  imports:
    - neo4j
    - neo4j.graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: 'Database connector for Neo4j graph database'
  dev_url: https://github.com/neo4j/neo4j-python-driver
  doc_url: https://neo4j.com/docs/api/python-driver/current/

extra:
  recipe-maintainers:
    - pvanheus
