{% set name = "neo4j" %}
{% set version = "6.2.0" %}

package:
  name: {{ name }}-suite
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-python-driver/archive/refs/tags/{{ version }}.tar.gz
  sha256: 3ce6681442fd30c19cee85691b580de566d30c62a580b7551ae3f8de845b70ad

build:
  number: 1

outputs:
  - name: neo4j-python-driver
    build:
      skip: true  # [py<310]
    script: build_base.sh  # [unix]
    script: build_base.bat  # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools >=82.0.1
        - wheel
      run:
        - python
        - pytz
      run_constrained:
        # pandas[timezone] is pandas + pytz:
        - pandas >=1.1.0,<4.0.0
        - pytz >=2024.2
        - numpy >=1.21.2,<3.0.0
        - pyarrow >=6.0.0,<25.0.0

    # E AttributeError: Attributes cannot start with 'assert' or 'assret'
    {% set tests_to_skip = "test_full_pool_re_auth_async or test_from_timestamp_without_tz" %}
    test:
      source_files:
        - tests
      imports:
        - neo4j
        - neo4j.graph
      commands:
        - pip check
        - pytest -vv -k "not ({{ tests_to_skip }})" tests/unit/common
      requires:
        - pip
        - pytest >=8.4.2
        - pytest-asyncio >=1.2.0
        - pytest-mock >=3.15.1
        - pandas >=1.1.0,<4.0.0
        - pytz >=2024.2
        - numpy >=1.21.2,<3.0.0
        - freezegun >=1.5.5
        - pyarrow >=6.0.0,<25.0.0
        - mock
  # neo4j AND neo4j-driver is the same pkgs.
  # https://pypi.org/project/neo4j/
  - name: {{ name }}
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('neo4j-python-driver', max_pin="x.x.x") }}
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - neo4j
        - neo4j.graph
  # https://pypi.org/project/neo4j-driver/
  - name: {{ name }}-driver
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('neo4j-python-driver', max_pin="x.x.x") }}
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - neo4j
        - neo4j.graph

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  description: |
    The official Neo4j driver for Python.
  summary: Database connector for Neo4j graph database
  dev_url: https://github.com/neo4j/neo4j-python-driver
  doc_url: https://neo4j.com/docs/api/python-driver/current/

extra:
  recipe-maintainers:
    - pvanheus
