{% set name='neo4j-python-driver' %}
{% set version='1.5.3' %}
{% set sha256='54098cfd99ddd21eeb65481e44fa7449948f7bb2a4af34d48e36822d3bc34fc2' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/neo4j/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - setuptools
  run:
    - python

test:
  imports:
    - neo4j
    - neo4j.bolt
    - neo4j.compat
    - neo4j.packstream
    - neo4j.v1

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: 'Database connector for Neo4j graph database'

extra:
  recipe-maintainers:
    - pvanheus
