{% set version = "4.2.1" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://github.com/neo4j/neo4j-python-driver/archive/{{ version }}.tar.gz
  sha256: 60e5a529e1262a1d73ff378c337d03dcf7bbd84b638e0ce5ace2f90846cdddc7

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - neotime

test:
  imports:
    - neo4j

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: 'Database connector for Neo4j graph database'

extra:
  recipe-maintainers:
    - pvanheus
