{% set version = "5.27.0" %}

package:
  name: neo4j-python-driver
  version: {{ version }}

source:
  url: https://github.com/neo4j/neo4j-python-driver/archive/{{ version }}.tar.gz
  sha256: cefd4296efe564b2feb96f628699e0cbf421888ba5815a1b92b2c1b5e71ff07d

build:
  number: 0
  skip: True  # [py<38]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - tomlkit
    - wheel
  run:
    - python
    - pytz

test:
  imports:
    - neo4j
    - neo4j.graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neo4j/neo4j-python-driver
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: 'Database connector for Neo4j graph database'
  dev_url: https://github.com/neo4j/neo4j-python-driver
  doc_url: https://neo4j.com/docs/api/python-driver/current/

extra:
  recipe-maintainers:
    - pvanheus
