travis:
  secure:
    BINSTAR_TOKEN: AED8Mgn2MqRWjwio6sqoVymeS0QhMFW5l25hURO+dG++sJ9XLZVZikv+i6lq4MBAKO+LtfZbb97PmSmZk4phF67tKKwr5YxyT79jux/uw4sLmOS8E2B6NWZ4lm2VtdF4HffWsCX0j0CXG0SrntsFUyWkzqRVgg9gX2QCh3EoKMZ3p7Xk25kzjHL2ECp0h6VFmn0Ku3XOyGUm+P39WBGaG8/0dXq6ca/YHrALlNsrGN4H4miQxFVQ2bJ918+0p99eMAYTYCkKM66oJpJL0XOWnEjhGpRdkzLfnb86nlew5PBqpESsESOnKPUKvTHg2wK3xz3sKAglWLN5qMX36Kro9Q9lSI2zbEYOMhVqaRtkhvbDiucpxm3WTHh+2+uE9fghCNoZgtpsERfVzAHHd4LeXinspRRTF2r918czDf0Z2outAhR/Cm+C3qlF7WTBprp6YQA8e1hfUW1uFgKMSUXrv4Xhb2o+4GA0ql/ZBsyf8Y8CeJsGYBxOMKOm1w42jNhfkRcfmvm/NY5sZBa/gzxxyNMQuwr1rhU4rG7boXWQgRoTqQDn/imILjvhF+OiPPlplt0WWkMC19pQ+TNXaUg6dC97ONAr/+XEcrnlyfbK3oOmQvouClu/5Q4xf7XbeTRfFq4xYtKhmjVrJaLFEKbAW29WE7AJ4iE1hFgBODvpG6c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
