travis:
  secure:
    BINSTAR_TOKEN: G4xxxGmI1xBcbik5xfXdxMvbBGYLsNacOkglNWxQd3eL8aegrI7kgRRdvipRAKy9CMGTHA8dpFfrNN3je3Ru1E+pOTDJmCScrW5dSUHHwpL+iVQFiMSghlo26yGvYTFxoj0+tsPQ+/e7LN8y3ySwMf2g9MDW7rQXBjfrr2bEEHUjqIAS2cnMzCF/pMNk/YWRqiT5hgVPIw/FactDpNeWgM2OP4NbfuoUT+bfdzYqHfHSQuCjpOCT8IVP8tWorbpmLvVi5u3bT+wOAeipgyXw1+ZuV2U+0V6JKgHZasQ5PcVqzpG8Sn6pql/7L8zII2YBi3mBN8ZYx4Kt/bdJAdCu31g7XcLLTIIyBU42E2nUL/ryuVJeCBuUjX4pPgvwXMym047esjKxtz2FApLHS8uV2m4ocBv8QQYYELB0mhTFjKSWLzMq5ITh17znum7RNwy5kClRa1H1AlCaAtABn+e28OAyJVYu+T37bQ3v5mmfVcYPOAIB47yL3EXkngy4qD6xP5pMXyZzdewkkOoyEuI8zorzVsA0NBaFqTaxgu+0pvVw16dBiUyk2YtLbLGOOa01scGMMyhQARJ3/91pxvUPO8oAiEKUWkLwy1I+CihRk6LYPdPg3sk4bEaBWibH6J/RgQqhXQGaZhClrKPvzZopYM607UjKk+jvr48H7hIhSSY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
